general:
   stop_string: bye
   gpt_engine: "davinci"
   gpt_temperature: 0.5
   gpt_max_tokens: 100
   gpt_key: <SET VALUE TO YOUR SECRET API KEY LISTED HERE https://beta.openai.com/developer-quickstart>
   