general:
   load_from_scratch: False
   save_raw_dataframe: False
   save_transformed_dataframe: True
   remove_bad_values: True
   stop_string: bye
   gpt_engine: "davinci"
   gpt_temperature: 0.5
   gpt_max_tokens: 100
   gpt_key: <YOU NEED TO SUPPLY YOUR KEY FROM https://beta.openai.com/developer-quickstart HERE>
   